version: "3"
services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gazzaotalk
      - MONGO_INITDB_ROOT_PASSWORD=gazzaotalk

  server:
    image: ghcr.io/gazzaotalk/server
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - MONGODB_URI=mongodb://gazzaotalk:gazzaotalk@db:27017/gazzaotalk
      - SECRET_KEY=${SECRET_KEY}

volumes:
  db-data:
